### ISSUE TITLE
Browser compatibility

### ISSUE THREAD

**Issue by petulla** [rdmurphy/frames#4]
hi Ryan

Which browsers are supported? Trying to get CNN to adopt for the amp support.

**Comment by rdmurphy** [comment]
Hey @petulla! Right now I believe it'll work anywhere [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) is supported due to it being added via the build process. So if y'all are already adding that to browsers that lack it you should be good to go.

However — I have a variation sitting in the `develop` branch I just need to push out as a new version that should introduce IE11 support without any extra work. (Basically a tiny Object.assign-esque function that gets the job done without adding much bloat.)

But overall this is a good general ask — I'll also work on adding to the README the target browsers for this.

**Comment by petulla** [comment]
Perfect. There's a critical mass of us internally who are looking to swap out Pym, and we're giving this  a hard look. I'll be looking for the develop branch merge as the version to prefer.

**Comment by rdmurphy** [comment]
@petulla `@newswire/frames@0.2.0` has been released with this change!

**Comment by petulla** [comment]
Awesome, thanks. I've sent to the internal team that works on our dailygraphics rig. Hoping to get it in, will keep you posted.

**Comment by rdmurphy** [comment]
@petulla 👍 Sounds good. Don't hesitate to shout if something is funky/could be better!

**Comment by petulla** [comment]
Making the PR today for this to our rig.. will keep you posted! @rdmurphy
